// Request state

const PENDING = '_PENDING';
const FULFILLED = '_FULFILLED';
const REJECTED = '_REJECTED';

// Classifier action
const PREFIX = 'CLASSIFIER'

export const GET_CLASSIFIER = `${PREFIX}/GET_CLASSIFIER_PAGE`;
export const GET_CLASSIFIER_PENDING = `${GET_CLASSIFIER}${PENDING}`;
export const GET_CLASSIFIER_FULFILLED = `${GET_CLASSIFIER}${FULFILLED}`;
export const GET_CLASSIFIER_REJECTED = `${GET_CLASSIFIER}${REJECTED}`;

export const GET_CLASSIFIER_VERSION_OR_PAGE = `${PREFIX}/CLASSIFIER_VERSION_OR_PAGE`;
export const GET_CLASSIFIER_VERSION_OR_PAGE_FULFILLED = `${GET_CLASSIFIER_VERSION_OR_PAGE}${FULFILLED}`;
export const GET_CLASSIFIER_VERSION_OR_PAGE_REJECTED = `${GET_CLASSIFIER_VERSION_OR_PAGE}${REJECTED}`;

export const GET_CLASSIFIER_BY_ID = `${PREFIX}/CLASSIFIER_ID`;
export const GET_CLASSIFIER_BY_ID_FULFILLED = `${GET_CLASSIFIER_BY_ID}${FULFILLED}`;
export const GET_CLASSIFIER_BY_ID_REJECTED = `${GET_CLASSIFIER_BY_ID}${REJECTED}`;

export const ACTIVE_CLASSIFIER = `${PREFIX}/ACTIVE_CLASSIFIER`;
export const ACTIVE_CLASSIFIER_FULFILLED = `${ACTIVE_CLASSIFIER}${FULFILLED}`;
export const ACTIVE_CLASSIFIER_REJECTED = `${ACTIVE_CLASSIFIER}${REJECTED}`;

export const CREATE_CLASSIFIER = `${PREFIX}/CREATE_CLASSIFIER`;
export const CREATE_CLASSIFIER_FULFILLED = `${CREATE_CLASSIFIER}${FULFILLED}`;
export const CREATE_CLASSIFIER_REJECTED = `${CREATE_CLASSIFIER}${REJECTED}`;

export const UPDATE_CLASSIFIER = `${PREFIX}/UPDATE_CLASSIFIER`;
export const UPDATE_CLASSIFIER_FULFILLED = `${UPDATE_CLASSIFIER}${FULFILLED}`;
export const UPDATE_CLASSIFIER_REJECTED = `${UPDATE_CLASSIFIER}${REJECTED}`;

export const DELETE_CLASSIFIER = `${PREFIX}/DELETE_CLASSIFIER`;
export const DELETE_CLASSIFIER_FULFILLED = `${DELETE_CLASSIFIER}${FULFILLED}`;
export const DELETE_CLASSIFIER_REJECTED = `${DELETE_CLASSIFIER}${REJECTED}`;

export const SUBMIT_NEW_TRAINING_MODEL = `${PREFIX}/SUBMIT_NEW_TRAINING_MODEL`;
export const SUBMIT_NEW_TRAINING_MODEL_FULFILLED = `${SUBMIT_NEW_TRAINING_MODEL}${FULFILLED}`;
export const SUBMIT_NEW_TRAINING_MODEL_REJECTED = `${PREFIX}${REJECTED}`;
