// Request state

const PENDING = '_PENDING';
const FULFILLED = '_FULFILLED';
const REJECTED = '_REJECTED';

// Prediction action
const PREFIX = 'PREDICTION'

export const MAKE_PREDICTION = `${PREFIX}/MAKE_PREDICTION`;
export const MAKE_PREDICTION_PENDING = `${MAKE_PREDICTION}${PENDING}`;
export const MAKE_PREDICTION_FULFILLED = `${MAKE_PREDICTION}${FULFILLED}`;
export const MAKE_PREDICTION_REJECTED = `${MAKE_PREDICTION}${REJECTED}`;

export const MAKE_PREDICTION_WITH_SPECIFIC_CLASSIFIER = `${PREFIX}/MAKE_PREDICTION_WITH_SPECIFIC_CLASSIFIER`;
export const MAKE_PREDICTION_WITH_SPECIFIC_CLASSIFIER_PENDING = `${MAKE_PREDICTION_WITH_SPECIFIC_CLASSIFIER}${PENDING}`;
export const MAKE_PREDICTION_WITH_SPECIFIC_CLASSIFIER_FULFILLED = `${MAKE_PREDICTION_WITH_SPECIFIC_CLASSIFIER}${FULFILLED}`;
export const MAKE_PREDICTION_WITH_SPECIFIC_CLASSIFIER_REJECTED = `${MAKE_PREDICTION_WITH_SPECIFIC_CLASSIFIER}${REJECTED}`;

export const GET_PREDICTION = `${PREFIX}/GET_PREDICTION`;
export const GET_PREDICTION_PENDING = `${GET_PREDICTION}${PENDING}`;
export const GET_PREDICTION_FULFILLED = `${GET_PREDICTION}${FULFILLED}`;
export const GET_PREDICTION_REJECTED = `${GET_PREDICTION}${REJECTED}`;

export const GET_PREDICTION_BY_ZUCCHINI_ID = `${GET_PREDICTION}_BY_ZUCCHINI_ID/`;
export const GET_PREDICTION_BY_ZUCCHINI_ID_PENDING = `${GET_PREDICTION_BY_ZUCCHINI_ID}${PENDING}`;
export const GET_PREDICTION_BY_ZUCCHINI_ID_FULFILLED = `${GET_PREDICTION_BY_ZUCCHINI_ID}${FULFILLED}`;
export const GET_PREDICTION_BY_ZUCCHINI_ID_REJECTED = `${GET_PREDICTION_BY_ZUCCHINI_ID}${REJECTED}`;

export const GET_PREDICTION_BY_SCENARIO_ID = `${GET_PREDICTION}_BY_SCENARIO_ID/`;
export const GET_PREDICTION_BY_SCENARIO_ID_PENDING = `${GET_PREDICTION_BY_SCENARIO_ID}${PENDING}`;
export const GET_PREDICTION_BY_SCENARIO_ID_FULFILLED = `${GET_PREDICTION_BY_SCENARIO_ID}${FULFILLED}`;
export const GET_PREDICTION_BY_SCENARIO_ID_REJECTED = `${GET_PREDICTION_BY_SCENARIO_ID}${REJECTED}`;

export const GET_PREDICTION_BY_CLASSIFIER_ID = `${GET_PREDICTION}_BY_CLASSIFIER_ID/`;
export const GET_PREDICTION_BY_CLASSIFIER_ID_PENDING = `${GET_PREDICTION_BY_CLASSIFIER_ID}${PENDING}`;
export const GET_PREDICTION_BY_CLASSIFIER_ID_FULFILLED = `${GET_PREDICTION_BY_CLASSIFIER_ID}${FULFILLED}`;
export const GET_PREDICTION_BY_CLASSIFIER_ID_REJECTED = `${GET_PREDICTION_BY_CLASSIFIER_ID}${REJECTED}`;
