// Request state

const PENDING = '_PENDING';
const FULFILLED = '_FULFILLED';
const REJECTED = '_REJECTED';

// Scenario action
const PREFIX = 'SCENARIO'

export const GET_SCENARIO = `${PREFIX}/GET_SCENARIO_PAGE`;
export const GET_SCENARIO_PENDING = `${GET_SCENARIO}${PENDING}`;
export const GET_SCENARIO_FULFILLED = `${GET_SCENARIO}${FULFILLED}`;
export const GET_SCENARIO_REJECTED = `${GET_SCENARIO}${REJECTED}`;

export const GET_SCENARIO_BY_ID = `${PREFIX}/GET_SCENARIO_BY_ID`;
export const GET_SCENARIO_BY_ID_PENDING = `${GET_SCENARIO_BY_ID}${PENDING}`;
export const GET_SCENARIO_BY_ID_FULFILLED = `${GET_SCENARIO_BY_ID}${FULFILLED}`;
export const GET_SCENARIO_BY_ID_REJECTED = `${GET_SCENARIO_BY_ID}${REJECTED}`;

export const UPDATE_SCENARIO = `${PREFIX}/UPDATE_SCENARIO`;
export const UPDATE_SCENARIO_PENDING = `${PREFIX}${PENDING}`;
export const UPDATE_SCENARIO_FULFILLED = `${PREFIX}${FULFILLED}`;
export const UPDATE_SCENARIO_REJECTED = `${PREFIX}${REJECTED}`;
